//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapaGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0573dcda3e126ff47d34a53e7742dc36_diseno_lindo_del_patron_de_conejos_de_pascua {
            get {
                object obj = ResourceManager.GetObject("0573dcda3e126ff47d34a53e7742dc36-diseno-lindo-del-patron-de-conejos-de-pascua", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _102647 {
            get {
                object obj = ResourceManager.GetObject("102647", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1026471 {
            get {
                object obj = ResourceManager.GetObject("1026471", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _14720 {
            get {
                object obj = ResourceManager.GetObject("14720", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _147201 {
            get {
                object obj = ResourceManager.GetObject("147201", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _147202 {
            get {
                object obj = ResourceManager.GetObject("147202", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _48629558_vector_sin_patrón_con_patas_de_animales_huellas_fondo {
            get {
                object obj = ResourceManager.GetObject("48629558-vector-sin-patrón-con-patas-de-animales-huellas-fondo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _52613719_colorida_huella_de_los_animales_ornamento_frontera_aislado_sobre_fondo_blanco_ilustración_del_vector_pa {
            get {
                object obj = ResourceManager.GetObject("52613719-colorida-huella-de-los-animales-ornamento-frontera-aislado-sobre-fondo-b" +
                        "lanco-ilustración-del-vector-pa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _52613719_colorida_huella_de_los_animales_ornamento_frontera_aislado_sobre_fondo_blanco_ilustración_del_vector_pa1 {
            get {
                object obj = ResourceManager.GetObject("52613719-colorida-huella-de-los-animales-ornamento-frontera-aislado-sobre-fondo-b" +
                        "lanco-ilustración-del-vector-pa1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _61333213_huellas_de_animales_de_colores_sin_patrón_ilustración_vectorial {
            get {
                object obj = ResourceManager.GetObject("61333213-huellas-de-animales-de-colores-sin-patrón-ilustración-vectorial", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _61333213_huellas_de_animales_de_colores_sin_patrón_ilustración_vectorial1 {
            get {
                object obj = ResourceManager.GetObject("61333213-huellas-de-animales-de-colores-sin-patrón-ilustración-vectorial1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _637_6378272_resultado_de_imagen_para_huellas_de_gato_png {
            get {
                object obj = ResourceManager.GetObject("637-6378272_resultado-de-imagen-para-huellas-de-gato-png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _657a92ae22e1d5ad5282f9ad87152664 {
            get {
                object obj = ResourceManager.GetObject("657a92ae22e1d5ad5282f9ad87152664", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _84138 {
            get {
                object obj = ResourceManager.GetObject("84138", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _841381 {
            get {
                object obj = ResourceManager.GetObject("841381", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8c4eb0e33d30f567281774b790efaadf {
            get {
                object obj = ResourceManager.GetObject("8c4eb0e33d30f567281774b790efaadf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8c4eb0e33d30f567281774b790efaadf1 {
            get {
                object obj = ResourceManager.GetObject("8c4eb0e33d30f567281774b790efaadf1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b986a0fdc106df160e6f7d1a351d2b9f {
            get {
                object obj = ResourceManager.GetObject("b986a0fdc106df160e6f7d1a351d2b9f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_icon_delete_button_png_picture_thumb {
            get {
                object obj = ResourceManager.GetObject("button-icon-delete-button-png-picture-thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cogs_and_gears_abstract_background_vector_in_blue_on_isolated_background {
            get {
                object obj = ResourceManager.GetObject("cogs-and-gears-abstract-background-vector-in-blue-on-isolated-background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap computer_icons_deviantart_music_download_left_arrow {
            get {
                object obj = ResourceManager.GetObject("computer-icons-deviantart-music-download-left-arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cursos_de_veterinaria_gratis_ {
            get {
                object obj = ResourceManager.GetObject("Cursos-de-veterinaria-gratis-", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap depositphotos_105699984_stock_illustration_vector_seamless_pattern_with_cat {
            get {
                object obj = ResourceManager.GetObject("depositphotos_105699984-stock-illustration-vector-seamless-pattern-with-cat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap descarga {
            get {
                object obj = ResourceManager.GetObject("descarga", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disquete_magnetico_icono_plano_100456_87 {
            get {
                object obj = ResourceManager.GetObject("disquete-magnetico-icono-plano_100456-87", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dsBuffer_bmp {
            get {
                object obj = ResourceManager.GetObject("dsBuffer.bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap e4687f0d09bb6a9ab195ae7e3905033a__paw_prints_cat_art {
            get {
                object obj = ResourceManager.GetObject("e4687f0d09bb6a9ab195ae7e3905033a--paw-prints-cat-art", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap editar {
            get {
                object obj = ResourceManager.GetObject("editar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fc1d3c601df8682264c4a3a4b2dbbd94_fondo_abstracto_del_engranaje {
            get {
                object obj = ResourceManager.GetObject("fc1d3c601df8682264c4a3a4b2dbbd94-fondo-abstracto-del-engranaje", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fondo_abstracto_mecanismo_rueda_engranaje_41981_300 {
            get {
                object obj = ResourceManager.GetObject("fondo-abstracto-mecanismo-rueda-engranaje_41981-300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gato_lindo_fondo_inconsutil_modelo_pastel_marron_45130_407 {
            get {
                object obj = ResourceManager.GetObject("gato-lindo-fondo-inconsutil-modelo-pastel-marron_45130-407", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap i_busqueda {
            get {
                object obj = ResourceManager.GetObject("i_busqueda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images {
            get {
                object obj = ResourceManager.GetObject("images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__1_ {
            get {
                object obj = ResourceManager.GetObject("images (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images1 {
            get {
                object obj = ResourceManager.GetObject("images1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images2 {
            get {
                object obj = ResourceManager.GetObject("images2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images3 {
            get {
                object obj = ResourceManager.GetObject("images3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lindo_gato_patrones_fisuras_44695_22 {
            get {
                object obj = ResourceManager.GetObject("lindo-gato-patrones-fisuras_44695-22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap papeles_pintados_fondo_transparente_con_huesos_coloridos_y_patas_de_perro_sobre_fondo_blanco_adecuado_para_papel_de_regalo_papel_tapiz_y_tarjeta_jpg {
            get {
                object obj = ResourceManager.GetObject("papeles-pintados-fondo-transparente-con-huesos-coloridos-y-patas-de-perro-sobre-f" +
                        "ondo-blanco-adecuado-para-papel-de-regalo-papel-tapiz-y-tarjeta.jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap papeles_pintados_fondo_transparente_con_huesos_coloridos_y_patas_de_perro_sobre_fondo_blanco_adecuado_para_papel_de_regalo_papel_tapiz_y_tarjeta1 {
            get {
                object obj = ResourceManager.GetObject("papeles-pintados-fondo-transparente-con-huesos-coloridos-y-patas-de-perro-sobre-f" +
                        "ondo-blanco-adecuado-para-papel-de-regalo-papel-tapiz-y-tarjeta1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Perro_gato_mascotas {
            get {
                object obj = ResourceManager.GetObject("Perro-gato-mascotas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_computer_icons_google_search_web_search_engine_world_wide_web_blue_search_engine_optimization_electric_blue {
            get {
                object obj = ResourceManager.GetObject("png-transparent-computer-icons-google-search-web-search-engine-world-wide-web-blu" +
                        "e-search-engine-optimization-electric-blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_computer_icons_google_search_web_search_engine_world_wide_web_blue_search_engine_optimization_electric_blue1 {
            get {
                object obj = ResourceManager.GetObject("png-transparent-computer-icons-google-search-web-search-engine-world-wide-web-blu" +
                        "e-search-engine-optimization-electric-blue1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_computer_icons_google_search_web_search_engine_world_wide_web_blue_search_engine_optimization_electric_blue2 {
            get {
                object obj = ResourceManager.GetObject("png-transparent-computer-icons-google-search-web-search-engine-world-wide-web-blu" +
                        "e-search-engine-optimization-electric-blue2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap seach {
            get {
                object obj = ResourceManager.GetObject("seach", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap seach1 {
            get {
                object obj = ResourceManager.GetObject("seach1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thumb2_paws_patterns_creative_footprints_patterns_abstract_backgrounds_dog_footprints__1_ {
            get {
                object obj = ResourceManager.GetObject("thumb2-paws-patterns-creative-footprints-patterns-abstract-backgrounds-dog-footpr" +
                        "ints (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vector_el_modelo_inconsútil_con_huellas_del_gato_o_del_perro_colorfu_lindo_82517658 {
            get {
                object obj = ResourceManager.GetObject("vector-el-modelo-inconsútil-con-huellas-del-gato-o-del-perro-colorfu-lindo-825176" +
                        "58", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
